# Generated by Django 4.0.6 on 2022-07-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, default=None, upload_to='')),
                ('data', models.TextField(blank=True, default=None)),
                ('rows', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'upload',
            },
        ),
    ]
